### ISSUE TITLE
Uncaught TypeError: Exception::__construct(): Argument #2 ($code) must be of type int, string given

### ISSUE THREAD

**Issue by NickGreen** [a8cteam51/plugin-autoupdate-filter#30]
## Synopsis

When the endpoint is not accessible, the error is causing a fatal:
```
[17-Apr-2024 22:38:11 UTC] PHP Fatal error:  Uncaught TypeError: Exception::__construct(): Argument #2 ($code) must be of type int, string given in /Users/nickgreen/Local Sites/testi/app/public/wp-content/plugins/plugin-autoupdate-filter-trunk/class-plugin-autoupdate-filter.php:81
Stack trace:
#0 /Users/nickgreen/Local Sites/testi/app/public/wp-content/plugins/plugin-autoupdate-filter-trunk/class-plugin-autoupdate-filter.php(81): Exception->__construct('cURL error 7: F...', 'http_request_fa...')
#1 /Users/nickgreen/Local Sites/testi/app/public/wp-content/plugins/plugin-autoupdate-filter-trunk/class-plugin-autoupdate-filter.php(21): Plugin_Autoupdate_Filter->get_auto_update_settings()
#2 /Users/nickgreen/Local Sites/testi/app/public/wp-content/plugins/plugin-autoupdate-filter-trunk/class-plugin-autoupdate-filter.php(305): Plugin_Autoupdate_Filter->init()
#3 /Users/nickgreen/Local Sites/testi/app/public/wp-content/plugins/plugin-autoupdate-filter-trunk/plugin-autoupdate-filter.php(19): require_once('/Users/nickgree...')
#4 /Users/nickgreen/Local Sites/testi/app/public/wp-settings.php(517): include_once('/Users/nickgree...')
#5 /Users/nickgreen/Local Sites/testi/app/public/wp-config.php(100): require_once('/Users/nickgree...')
#6 /Users/nickgreen/Local Sites/testi/app/public/wp-load.php(50): require_once('/Users/nickgree...')
#7 /Users/nickgreen/Local Sites/testi/app/public/wp-blog-header.php(13): require_once('/Users/nickgree...')
#8 /Users/nickgreen/Local Sites/testi/app/public/index.php(17): require('/Users/nickgree...')
#9 {main}
  thrown in /Users/nickgreen/Local Sites/testi/app/public/wp-content/plugins/plugin-autoupdate-filter-trunk/class-plugin-autoupdate-filter.php on line 81
```

## Details
Line of code: [https://github.com/a8cteam51/plugin-autoupdate-filter/blob/0bd2a0fa3968f1d55bb3553c22036f905d7efc05/class-plugin-autoupdate-filter.php#L81](https://github.com/a8cteam51/plugin-autoupdate-filter/blob/0bd2a0fa3968f1d55bb3553c22036f905d7efc05/class-plugin-autoupdate-filter.php#L81)

PHP Exceptions need an int as a status code … whereas WP_Error usually has a text code

## Fix

The second argument here probably doesn't even need to be there: 
`throw new RuntimeException( $response->get_error_message(), $response->get_error_code() );`

**Comment by NickGreen** [comment]
Fixed with https://github.com/a8cteam51/plugin-autoupdate-filter/pull/31
